class UserAlreadyExistsError(Exception):
    pass


class UserDoesNotExistError(Exception):
    pass
